- NEMbox/api.py
- NEMbox/ui.py
将硬盘存储的密码改为MD5哈希之后的密码形式.
在硬盘上明文存储密码不是一个好主意,应当储存哈希后的密码值
__注意此patch将导致已登陆用户需要重新登陆__
> 使用非明文方式存储密码

- NEMbox/const.py
- NEMbox/logger.py
As I start musicbox under different directories, a log file will be created under the current directory. It is quite inconvenient to rm it every time, so I mv it to a const directory. 
Hope to be helpful :-)
> changed the directory of musicbox.log

- NEMbox/api.py
- NEMbox/menu.py
If I trying to enter next level of menu while datalist is empty, it caused an exception. For example, in the search menu and choose any of them except "歌曲", for example, I choose "网易精选集"![search](http://7xo6r2.com1.z0.glb.clouddn.com/15-11-9/8469521.jpg)
and then, i just press enter, ![nothing](http://7xo6r2.com1.z0.glb.clouddn.com/15-11-9/8982652.jpg) nothing found, but as a result, the datatype became "top_playlists" and datalist became empty, base on the code
```python
if idx == 0:
self.datatype = 'top_playlists'
self.datalist = ui.build_search('search_playlist')
self.title = '精选歌单搜索列表'
```
if I press enter in this ui, it will cause an exception when try to access `datalist[0]['playlist_id']`
because code is as following, 
```python
elif datatype == 'top_playlists':
log.debug(datalist) …
```
> fixed the exception caused by trying to enter next level while datalist is empty

- NEMbox/menu.py
- NEMbox/player.py
- NEMbox/ui.py
If a song is played to the end or ']'  is pressed , playing song will be the next of the playing_list. If ui is still "at_playing_list", the highlight row will be updated to the current playing song.For example, if the current playing song is “好好的”
then if user press ']' and if the playing mode is sequence, then “红色高跟鞋” will be highlighted.
if there exist a single quote in the song name or album name or artist name, like I'll show you, the notification will not work, and some error message will be printed on the screen because of the escape problem. Like the following image.
the single quotation mark can be escaped by replace it to \', and should put a $ before the string to indicate we want to use escape in the string, but double quotation mark problem can not be solved by replace it to …
> keep track of playing song and fixed the notification bug

- NEMbox/player.py
- NEMbox/ui.py
Add app name
Put song info into message body
在 GNOME 3 上面显示效果更好了一点，解决了专辑名和歌手名显示不全的问题。其他桌面环境欢迎测试～
> Modify notify-send message

- NEMbox/api.py
用内置的快速幂取模函数来加密，效率会更高些。以下改进前和改进后运行的时间：
```bash
$ python test.py
NEW: --- 0.0 seconds ---
OLD: --- 5.15600013733 seconds ---
True
$ python test.py
NEW: --- 0.0 seconds ---
OLD: --- 5.16900014877 seconds ---
True
$ python test.py
NEW: --- 0.0 seconds ---
OLD: --- 5.17399978638 seconds ---
True
```
文档：https://docs.python.org/2/library/functions.html#pow
> Built-in function pow are more efficiently than x ^ y % z.

- setup.py
@darknessomi 
之前出错是因为没有这个参数就无法获取到 `requirements.txt` 文件。
```
HERE = os.path.abspath(os.path.dirname(__file__))
def get_install_requires(filename):
req = []
path = os.path.join(HERE, filename)
if os.path.exists(path):
with open(path) as f:
req = [l.strip() for l in f.xreadlines() if not l.isspace()]
return req
```
我之前的这个写法没测出bug是因为我一直都是直接用 python setup.py install 或者 python setup.py develop 测试（目录下必然存在`requirements.txt`文件）。
查了下资料，不推荐通用`requirements.txt`文件内容和`install_requires`，所以干脆就不用了。
ref: http://python-packaging-user-guide.readthedocs.org/en/latest/requirements/
既然不需要`requirements.txt`文件了，那么`include_package_data=True`也就不需要了。
ps: 猜测官方默认设置这个为False大概是希望Python的包会比较纯粹？不晓得。
> rm include_package_data=True

- NEMbox/api.py
param `limit` of search api is always set to `60`, this pr will fix it.
@darknessomi please review.
> fix limit param of search api

- NEMbox/menu.py
keybinder is written in C and Python 2.5, which introduces lots of potential GTK error like #361 #362 #353 
@darknessomi 
PS.
May we use TravisCI to automatically deploy package on PyPi?
> [Fix] deprecate keybinder

- NEMbox/menu.py
主要是为了方便复制出去的链接能被其他链接预览服务抓取歌曲信息。
> fix music url to open

- NEMbox/api.py
```
Return x to the power y; if z is present, return x to the power y, modulo z (computed more efficiently than pow(x, y) % z).
```
> use `pow` argument `modulo` instead of %

- NEMbox/api.py
网易云音乐登陆地址已更新，原地址为：'https://music.163.com/weapi/login/' ，  
更新后地址为：action = 'https://music.163.com/weapi/login?csrf_token='，
csrf_token从session中获取，经测试，csrf_token为空时也可登陆。
> 网易云音乐登陆地址更新

- NEMbox/ui.py
原来的UI在即使窗口大小没有改变的情况下也会每隔500ms调用 curses.resizeterm， 致使 ncurses 重绘整个窗口，导致终端历史被刷屏，并且增加终端的 CPU 占用率。这个 PR 修正了这个问题。
> 仅当窗口大小改变的时候调整terminal的大小

- NEMbox/osdlyrics.py
Move the window to the bottom center of the screen by default, fix #388. Put lyrics and translation into separate lines.
> Adjust osdlyrics, fix window position and lyrics translation

- NEMbox/player.py
- NEMbox/utils.py
捕获通知命令无法找到的异常，避免 RaspberryPI 一类的系统无法找到通知
命令，报错影响程序界面。
同时为方便异常捕获，改为使用 subprocess 调用命令。
修复 `[Errno 32] Broke pipe` 引起的程序异常退出。 
Resolves: #465 
See also: #81
> [fix]捕获通知命令无法找到的异常

- NEMbox/config.py
- NEMbox/osdlyrics.py
Osdlyrics area is too small in hidpi screen,  such as my Thinkpad (2560*1440), Specially the height is not enough，so I add the config to control the osdlyrics area size.
> add config for osdlyrics background area size

- NEMbox/__init__.py
现有的命令行参数解析是在包导入时做的，会影响到试图 import 这个包的外部用户。
> Moves argument parsing into start

- NEMbox/ui.py
增加双行显示功能，这样体验上和正常的桌面音乐播放器歌词显示类似了
> [new_feature]增加歌词双行显示功能

- NEMbox/ui.py
> [fix] 搜索时报 UnicodeWarning

- setup.py
感谢命令行版网易云~, 体验感很不错~, 修改了一点小的bug, 使用到精选歌单分类下的分类精选功能时，会提示lxml包依赖缺失，在install_requires中依赖缺失lxml, 特补充完整.
> fix:修复了 精选歌单>分类精选 功能下,lxml包依赖的缺失

- NEMbox/ui.py
翻译后的语句是`tline`，但是两个`tline`显然是一样的，这造成了翻译歌词显示的错误。
两行不同的歌词，中文翻译总是一样的。
***
修复前效果：
修复后效果：
> 修复Issue#601双行翻译歌词的问题

- NEMbox/menu.py
- NEMbox/scrollstring.py
2017-12-12：
您好，还是感谢musicbox带来的流畅体验~，但使用过程中发现，有些名字过长的音乐名不会滚动播放，发现关于中文字符长度的计算问题，特将此修正。
2017-12-13：
哈，真是爱死musicbox了。刚刚发现如果前进目录已经为空了，还是会执行一次前进操作，同时还可以执行一次多余的回退操作，感觉这样对于用户的体验感不是很好，所以我尝试着将这个功能小小地修正了一下，如果前进目录不存的话，就忽略此次前进操作了。thx
> [fix]:修正了中文字符计算错误的问题.[new_feature]:关于前进操作的小修改.

- NEMbox/api.py
播放和显示歌曲不一致是因为网站 api 返回的 urls 的 id 顺序和 data 的 id 顺序不一致
我自己的列表中有些云盘的歌曲歌手名是 None，会导致程序崩溃
{'name': '嘻哈空姐', 'id': 31393802, 'pst': 0, 't': 1, 'ar': [{'id': 0, 'name': None, 'tns': [], 'alias': []}], 'alia': [], 'pop': 0.0, 'st': 0, 'rt': None, 'fee': 0, 'v': 7, 'crbt': None, 'cf': None, 'al': {'id': 0, 'name': None, 'picUrl': None, 'tns': [], 'pic': 0}, 'dt': 168000, 'h': None, 'm': None, 'l': {'br': 192000, 'fid': 0, 'size': 4046262, 'vd': 0.0}, 'a': None, 'cd': None, 'no': 0, 'rtUrl': None, 'ftype': 0, 'rtUrls': [], 'djId': 0, 'copyright': 0, 's_id': -185674, 'mst': 9, 'cp': 0, 'mv': 0, 'rtype': 0, 'rurl': None, 'publishTime': 0, 'pc': {'nickname': '', 'version': 1, 'br': 192, 'cid': '', 'alb': '', 'sn': '嘻哈空姐', 'ar': '周杰伦', 'fn': '嘻哈空姐 www.is123.cn.mp3', 'uid': 41533322}, 'url': …
> 修复播放和显示歌曲不一致，修复加载某些歌手名为 None 的歌曲导致崩溃的问题

- NEMbox/ui.py
- README.md
我的环境是python3.7，Linux bogon 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux，使用mpg123 1.25.10的时候，始终显示[32] broken pipe,单独测试了这一版本的mpg123，发现会有找不到硬件的问题，改用低版本的软件后正常使用。
> mpg123 版本问题

- NEMbox/api.py
- NEMbox/const.py
- NEMbox/menu.py
1、修复歌单详情只有一首歌；
2、缓存文件路径修改至~/.netseae-musicbox/nemcache.sqlite，而不是当前文件夹下的nemcache.sqlite；
3、将旧版的每日推荐歌曲（非歌单）添加至当前版本
> 修复歌单bug修改缓存路径

- NEMbox/api.py
在 Cookie 中传入 `rest=None` 会在存储 cookie 时导致抛出异常。因为标准库期望 `rest` 是一个 dict-like： https://github.com/python/cpython/blob/f1f9c0c532089824791cfc18e6d6f29e1cd62596/Lib/http/cookiejar.py#L1846
Should fix https://github.com/darknessomi/musicbox/issues/824 and https://github.com/darknessomi/musicbox/issues/809
> 修复 Python 3 登录问题

- NEMbox/menu.py
systemd send SIGTERM to all processes when system shutdown. We should
handle this signal, save player's status before shutdown.
> fix: handle SIGTERM signal.

- NEMbox/api.py
根据 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) 中 [login_cellphone.js](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/login_cellphone.js) 的最新提交得出 `countrycode` 属性必选项的缺失导致手机登录api失效，现已修复该问题。
> 修复了手机无法登录的Bug，添加countrycode='86'必选属性

- NEMbox/ui.py
There is a small typo in NEMbox/ui.py.
Should read `scroll` rather than `scoll`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, scoll -> scroll

- NEMbox/ui.py
Time string from lyric_line is invalid in some case.
For example, '99:00.00' which does not match format '%M:%S.%f'.
Here to update the regex to match valid time only which is range from 0-59 .
fix #936
Signed-off-by: hoyho <luohaihao@gmail.com>
> fix: parse invalid lyric timestamp failed
