- src/api.py
- src/ui.py
> Add phone_login interface

- setup.py
- src/api.py
- src/ui.py
> 支持部分手机注册用户登录

- README.md
- setup.py
- src/menu.py
- src/player.py
Use 'mpg123 -R' instead of 'mpg123' to send control mesage to mpg123.
Use stdin to Load music, control Volume and detection music's end.
In order to detection music's end. Instead "popen_handler.wait()" with
"while(true) popen_handler.stdout.readline"
> Add Volume Control.

- README.md
- src/menu.py
- src/ui.py
> Unity Search UI

- NEMbox/menu.py
- NEMbox/ui.py
- README.md
想要调整本地收藏里面的曲子的顺序想了很久了……
今天闲下来就把这个写了上去，求采纳 O_O
> 向上/向下移动项目功能

- NEMbox/api.py
- NEMbox/player.py
- NEMbox/ui.py
想了想还是把我自己写的高音质播放实现推上来了，相对原来主要有以下几个改进：
- 使用了重写的encrypt_id，原来的这个函数应该是GPL的，因此不重写直接在MIT项目里引用的话是违反协议的……虽然应该不会有管这个啦
- 生成下载地址时从网易的m1,m2服务器随机挑一个用，这样网络流量更均衡些吧……
- 在UI里面添加了一个显示当前正在播放的音乐的音质与码率的功能
> 播放时显示当前音质与码率

- NEMbox/menu.py
You can resume your last songs by press 'p' when you reopen the program.
应该没啥大的问题，更新后需要重新登陆一次。
> Add Resume Function

- NEMbox/api.py
reason: data[i]['album'] could be empty
> fix 歌手列表:李志crash bug

- NEMbox/__init__.py
> clean up terminal while failed

- NEMbox/menu.py
- NEMbox/player.py
- NEMbox/scrollstring.py
- NEMbox/ui.py
Here's the demo:
The menu part should work flawlessly. I have figured out the cause of the issue (here)[https://github.com/darknessomi/musicbox/issues/70], and noted it down in ```build_playinfo``` function.
> The ability to scroll the long song names in the menu

- NEMbox/menu.py
- NEMbox/player.py
- NEMbox/ui.py
增加播放条。。。
不过异常难看，需要调整调整位置什么的。而且长度也是固定的不是自动匹配的。
> add process bar

- NEMbox/menu.py
- NEMbox/player.py
- NEMbox/ui.py
the list self.songs out of range.
> Fix bug of break when press "[/]" when app start

- NEMbox/menu.py
- NEMbox/player.py
- NEMbox/storage.py
- NEMbox/ui.py
> Add storage class to manage data of songs, player info, etc

- NEMbox/menu.py
- NEMbox/player.py
- setup.py
> Fix play/pause bug when press ' ' at the same song

- NEMbox/cache.py
- NEMbox/const.py
- NEMbox/menu.py
- NEMbox/player.py
- NEMbox/storage.py
1、使用的是aria2c 下载的。
2、database更新到version 2.
3、默认cache功能是关闭的，需要手工修改database中的cache 从 false -> true
4、缓存方式是听一首开始缓存一首，也就是缓存没有上限。
如果我们认为我们把曲子放在了隐藏文件夹里是不提供下载的话，我觉得倒是可以开启默认缓存的功能。
> Add cache function

- NEMbox/api.py
- NEMbox/menu.py
> 去掉了不常用的打碟功能，添加了每日推荐功能

- NEMbox/api.py
> 增加了私人FM API

- NEMbox/api.py
- NEMbox/cache.py
- NEMbox/menu.py
- NEMbox/player.py
- NEMbox/ui.py
Add callback when all songs finished
Add fm_callback to auto require new songs
Change some logic.
> Add new datatype: fmsongs

- NEMbox/api.py
- NEMbox/menu.py
- NEMbox/player.py
Update Login Logic
Fix bug of error pause_status at switch to next songs when pause
> Update Login Logic

- NEMbox/config.py
- NEMbox/menu.py
添加了全局快捷键
全局快捷键处理起来比较麻烦……于是直接用了[keybinder](https://github.com/engla/keybinder)项目的代码，虽然这个项目快没什么维护的样子，但是感觉不是一个很复杂的项目，是用GTK的方法进行快捷键绑定的，如果有问题的话我可以帮助维护这个项目
写的代码中有检查keybinder是否安装的代码， 如果未安装就不会进行全局快捷键绑定，因此，可以把keybinder列为optional dependency
已在Arch Linux平台上测试通过， 测试使用包community/python2-keybinder2
> Added global hotkeys, using python2-keybinder

- NEMbox/ui.py
如果用`os.system`的话，就不需要`subprocess`模块和fnull了……稍微Clean up了一下
> Cleanup unused modules

- NEMbox/player.py
update songs info in database if mp3_url is not same
> Update Append_Songs Function

- NEMbox/menu.py
> 添加I键打开当前音乐信息页面

- NEMbox/menu.py
- NEMbox/player.py
新增一个命令，支持在未开启全量cache时，手动通过"C"来cache单首
> add command 'C' for cache song

- .gitignore
- NEMbox/api.py
> Update Recommend API from traditional to encryped.

- NEMbox/api.py
- NEMbox/player.py
- NEMbox/storage.py
- NEMbox/ui.py
Shown as
Translated lyrics // Original lyrics
> Add translated lyrics

- NEMbox/menu.py
避免在精选歌单等界面下使用数字快捷键造成的IndexError（渣改...）
> 增加判断条件，避免数字快捷键导致的 out of list index

- NEMbox/player.py
Switch from SIGNAL CONTROL to COMMAND CONTROL
> Change Player's Pause/Resume Function

- NEMbox/menu.py
> add existing song notification

- NEMbox/api.py
- NEMbox/menu.py
- NEMbox/player.py
修复 #284 会跳过非中文和英文歌的问题。
没有改动原有的API，只是增加了2个函数（`NetEase.songs_detail_new_api`和`geturl_new_api`）以新API获取地址（`geturl_new_api`是根据原来的歌曲信息的id获取新API的播放地址，这个函数目前还没有被使用）。
方法：
在`player.py`里面增加判断，如果mpg123提示@E（播放错误），就用新API获取一个替代的URL播放。
> Fix old api issue

- NEMbox/__init__.py
- NEMbox/api.py
- NEMbox/cache.py
- NEMbox/logger.py
- NEMbox/menu.py
- NEMbox/terminalsize.py
- NEMbox/ui.py
- 下载全部用新API
- 部分过长的字符串改用`str.format`拼接
> Minor change

- NEMbox/__init__.py
- NEMbox/api.py
- NEMbox/cache.py
- NEMbox/config.py
- NEMbox/const.py
- NEMbox/logger.py
- NEMbox/menu.py
- NEMbox/osdlyrics.py
- NEMbox/player.py
- NEMbox/scrollstring.py
- NEMbox/singleton.py
- NEMbox/storage.py
- NEMbox/terminalsize.py
- NEMbox/ui.py
- NEMbox/utils.py
- requirements.txt
- setup.py
Add Python2 compatible support
> Python2and3

- NEMbox/__init__.py
- NEMbox/api.py
- NEMbox/menu.py
- NEMbox/ui.py
添加查看歌曲评论功能，在歌曲列表中enter进入即可查看该歌曲评论。
> 添加查看歌曲评论功能

- NEMbox/menu.py
- NEMbox/player.py
当添加歌曲到“我喜爱的音乐”时显示歌曲名，以免添加错误的歌曲。
> show song name when add song to likes

- NEMbox/ui.py
> [fix]小分辨率下评论显示错乱

- README.md
> 添加无法登录解决方法到readme

- NEMbox/api.py
借鉴自：https://github.com/Binaryify/NeteaseCloudMusicApi/commit/a1239a838c97367e86e2ec3cdce5557f1aa47bc1
thx!
> fix: 修正各个播放列表只有一首歌曲的问题

- README.md
Add shell command to help users to check logs by themselves so that they may solve the problem by themselves.
> README: add command for log checking

- NEMbox/api.py
在音乐云盘中上传了歌曲并添加到歌曲列表以后获取不到 'mp3Url', 暂时过滤这种音乐.
> 修复问题: https://github.com/darknessomi/musicbox/issues/642

- NEMbox/api.py
Commont out a notify in api.py line:558;
it will cause notify "need log in "
> fix 618 627

- NEMbox/api.py
- NEMbox/menu.py
原检测更新接口无法返回数据导致抛出异常，使用新的 JSON API 修复该问题。
> Fix version check. #690 #691 #688

- .gitignore
- NEMbox/__init__.py
- NEMbox/__version__.py
- NEMbox/api.py
- NEMbox/cache.py
- NEMbox/config.py
- NEMbox/encrypt.py
- NEMbox/logger.py
- NEMbox/menu.py
- NEMbox/osdlyrics.py
- NEMbox/player.py
- NEMbox/storage.py
- NEMbox/terminalsize.py
- NEMbox/tests/test_api.py
- NEMbox/ui.py
- README.md
- requirements.txt
- setup.py
- Use new version api thanks to https://binaryify.github.io/NeteaseCloudMusicApi
- Fix some function breakage
- Remove beautifulsoup dependency since every request is based on api
- Refactor menu, player and some ui
> Refactor lots of code 

- NEMbox/player.py
> fix: fix python2.7* random mode next song crash

- .circleci/config.yml
- NEMbox/__init__.py
- NEMbox/__main__.py
- NEMbox/__version__.py
- NEMbox/api.py
- NEMbox/cache.py
- NEMbox/config.py
- NEMbox/const.py
- NEMbox/encrypt.py
- NEMbox/logger.py
- NEMbox/menu.py
- NEMbox/osdlyrics.py
- NEMbox/player.py
- NEMbox/scrollstring.py
- NEMbox/singleton.py
- NEMbox/storage.py
- NEMbox/terminalsize.py
- NEMbox/ui.py
- NEMbox/utils.py
- README.md
- create_venv.sh
- setup.py
- 增加Circle CI
- 用black格式化代码
- 建议Lock住master分支 @darknessomi
> [Add] circle ci

- NEMbox/api.py
参考：https://github.com/Binaryify/NeteaseCloudMusicApi/commit/498080cab7e098c402bd103ef18b8549a0999d2d
> fix:修复登录460问题

- NEMbox/api.py
相关 issue
https://github.com/darknessomi/musicbox/issues/872
参考
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/login.js
> 修复登录失败，code 250，当前登录失败，请稍后再试

- README.md
sudo yum install -y python3-devel
> Update README.md 增加依赖包python3-devel
